### ISSUE TITLE
When trying to publish, an error is encountered

### ISSUE THREAD

**Issue by StacySimmons** [newrelic/newrelic-azure-devops-statistics#5]
## Description
Azure CLI reports the following error messages when attempting to publish the function (step 12):
```
Can't determine project language from files. Please use one of [--csharp, --javascript, --typescript, --java, --python, --powershell, --custom]
You're trying to use v4 tooling to publish to a non-v4 function app (FUNCTIONS_EXTENSION_VERSION is set to ~3).
You can pass --force to force update the app to v4, or downgrade tooling for publishing.
```

## Steps to Reproduce

Installation step 12 executed. 

## Relevant Logs / Console output
Azure Functions portal also displays this warning:
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/24992650/181109524-66041397-e74e-4c25-8b4d-c3dc23d3c3e9.png">

**Comment by kidk** [comment]
Thanks @StacySimmons I've pushed some changes to the repo that should resolve these issues. 

The installation doc as been updated and I've updated the reference bundle.
